[2018-10-09 01:10:07,509] {models.py:167} INFO - Filling up the DagBag from /home/ec2-user/Deep_Images_Hub/airflow/workspace/airflow_home/dags/Batch_Image_submissions.py
[2018-10-09 01:10:07,729] {base_task_runner.py:112} INFO - Running: ['bash', '-c', u'airflow run Batch_image_submission_simulation Data_file_prep 2018-10-09T01:10:03.059628 --job_id 4 --raw -sd DAGS_FOLDER/Batch_Image_submissions.py']
[2018-10-09 01:10:07,934] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:07,934] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-10-09 01:10:08,207] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:08,207] {models.py:167} INFO - Filling up the DagBag from /home/ec2-user/Deep_Images_Hub/airflow/workspace/airflow_home/dags/Batch_Image_submissions.py
[2018-10-09 01:10:08,426] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:08,426] {models.py:1126} INFO - Dependencies all met for <TaskInstance: Batch_image_submission_simulation.Data_file_prep 2018-10-09 01:10:03.059628 [queued]>
[2018-10-09 01:10:08,428] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:08,428] {models.py:1126} INFO - Dependencies all met for <TaskInstance: Batch_image_submission_simulation.Data_file_prep 2018-10-09 01:10:03.059628 [queued]>
[2018-10-09 01:10:08,428] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:08,428] {models.py:1318} INFO - 
[2018-10-09 01:10:08,428] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-10-09 01:10:08,428] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 1
[2018-10-09 01:10:08,428] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-10-09 01:10:08,429] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:10:08,440] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:08,439] {models.py:1342} INFO - Executing <Task(BashOperator): Data_file_prep> on 2018-10-09 01:10:03.059628
[2018-10-09 01:10:08,450] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:08,450] {bash_operator.py:71} INFO - tmp dir root location: 
[2018-10-09 01:10:08,450] {base_task_runner.py:95} INFO - Subtask: /tmp
[2018-10-09 01:10:08,451] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:08,451] {bash_operator.py:80} INFO - Temporary script location :/tmp/airflowtmprEBaDW//tmp/airflowtmprEBaDW/Data_file_prepz8WNq5
[2018-10-09 01:10:08,451] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:08,451] {bash_operator.py:81} INFO - Running command: 
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: split -l 160 ~/all_labels.txt ~/sample_labels_
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: peg scp to-rem pySpark-cluster 1 ~/sample_labelsaa /home/ubuntu/sample_labels_aa
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: peg scp to-rem pySpark-cluster 2 ~/sample_labelsab /home/ubuntu/sample_labels_ab
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: peg scp to-rem pySpark-cluster 3 ~/sample_labelsac /home/ubuntu/sample_labels_ac
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: peg scp to-rem pySpark-cluster 4 ~/sample_labelsad /home/ubuntu/sample_labels_ad
[2018-10-09 01:10:08,452] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:10:08,455] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:08,455] {bash_operator.py:90} INFO - Output:
[2018-10-09 01:10:09,502] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:09,502] {bash_operator.py:94} INFO - /home/ec2-user/sample_labelsaa: No such file or directory
[2018-10-09 01:10:10,354] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:10,354] {bash_operator.py:94} INFO - /home/ec2-user/sample_labelsab: No such file or directory
[2018-10-09 01:10:11,174] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:11,174] {bash_operator.py:94} INFO - /home/ec2-user/sample_labelsac: No such file or directory
[2018-10-09 01:10:12,022] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:12,022] {bash_operator.py:94} INFO - /home/ec2-user/sample_labelsad: No such file or directory
[2018-10-09 01:10:12,027] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:12,023] {bash_operator.py:97} INFO - Command exited with return code 1
[2018-10-09 01:10:12,027] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:12,024] {models.py:1417} ERROR - Bash command failed
[2018-10-09 01:10:12,027] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-10-09 01:10:12,027] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1374, in run
[2018-10-09 01:10:12,027] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-10-09 01:10:12,027] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 100, in execute
[2018-10-09 01:10:12,027] {base_task_runner.py:95} INFO - Subtask:     raise AirflowException("Bash command failed")
[2018-10-09 01:10:12,027] {base_task_runner.py:95} INFO - Subtask: AirflowException: Bash command failed
[2018-10-09 01:10:12,027] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:12,025] {models.py:1441} INFO - Marking task as FAILED.
[2018-10-09 01:10:12,039] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:10:12,038] {models.py:1462} ERROR - Bash command failed
[2018-10-09 01:10:12,039] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-10-09 01:10:12,039] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/bin/airflow", line 28, in <module>
[2018-10-09 01:10:12,039] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-10-09 01:10:12,039] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/bin/cli.py", line 422, in run
[2018-10-09 01:10:12,039] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-10-09 01:10:12,039] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-10-09 01:10:12,040] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-10-09 01:10:12,040] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1374, in run
[2018-10-09 01:10:12,040] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-10-09 01:10:12,040] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 100, in execute
[2018-10-09 01:10:12,040] {base_task_runner.py:95} INFO - Subtask:     raise AirflowException("Bash command failed")
[2018-10-09 01:10:12,040] {base_task_runner.py:95} INFO - Subtask: airflow.exceptions.AirflowException: Bash command failed
[2018-10-09 01:10:12,734] {jobs.py:2083} INFO - Task exited with return code 1
