[2018-10-09 01:04:31,099] {models.py:167} INFO - Filling up the DagBag from /home/ec2-user/Deep_Images_Hub/airflow/workspace/airflow_home/dags/Batch_Image_submissions.py
[2018-10-09 01:04:31,474] {base_task_runner.py:112} INFO - Running: ['bash', '-c', u'airflow run Batch_image_submission_simulation Data_file_prep 2018-10-09T01:04:23.991025 --job_id 2 --raw -sd DAGS_FOLDER/Batch_Image_submissions.py']
[2018-10-09 01:04:31,699] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:31,699] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-10-09 01:04:32,068] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:32,067] {models.py:167} INFO - Filling up the DagBag from /home/ec2-user/Deep_Images_Hub/airflow/workspace/airflow_home/dags/Batch_Image_submissions.py
[2018-10-09 01:04:32,355] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:32,355] {models.py:1126} INFO - Dependencies all met for <TaskInstance: Batch_image_submission_simulation.Data_file_prep 2018-10-09 01:04:23.991025 [queued]>
[2018-10-09 01:04:32,357] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:32,357] {models.py:1126} INFO - Dependencies all met for <TaskInstance: Batch_image_submission_simulation.Data_file_prep 2018-10-09 01:04:23.991025 [queued]>
[2018-10-09 01:04:32,357] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:32,357] {models.py:1318} INFO - 
[2018-10-09 01:04:32,357] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-10-09 01:04:32,358] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 1
[2018-10-09 01:04:32,358] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-10-09 01:04:32,358] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:04:32,369] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:32,369] {models.py:1342} INFO - Executing <Task(BashOperator): Data_file_prep> on 2018-10-09 01:04:23.991025
[2018-10-09 01:04:32,380] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:32,380] {bash_operator.py:71} INFO - tmp dir root location: 
[2018-10-09 01:04:32,380] {base_task_runner.py:95} INFO - Subtask: /tmp
[2018-10-09 01:04:32,381] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:32,381] {bash_operator.py:80} INFO - Temporary script location :/tmp/airflowtmpxUhi5r//tmp/airflowtmpxUhi5r/Data_file_prepRonRZJ
[2018-10-09 01:04:32,381] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:32,381] {bash_operator.py:81} INFO - Running command: 
[2018-10-09 01:04:32,381] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:04:32,381] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:04:32,381] {base_task_runner.py:95} INFO - Subtask: split -l 160 ~/all_labels.txt sample_labels_
[2018-10-09 01:04:32,381] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:04:32,382] {base_task_runner.py:95} INFO - Subtask: peg scp to-rem pySpark-cluster 1 ~/sample_labelsaa /home/ubuntu/sample_labels_aa
[2018-10-09 01:04:32,382] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:04:32,382] {base_task_runner.py:95} INFO - Subtask: peg scp to-rem pySpark-cluster 2 ~/sample_labelsab /home/ubuntu/sample_labels_ab
[2018-10-09 01:04:32,382] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:04:32,382] {base_task_runner.py:95} INFO - Subtask: peg scp to-rem pySpark-cluster 3 ~/sample_labelsac /home/ubuntu/sample_labels_ac
[2018-10-09 01:04:32,382] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:04:32,382] {base_task_runner.py:95} INFO - Subtask: peg scp to-rem pySpark-cluster 4 ~/sample_labelsad /home/ubuntu/sample_labels_ad
[2018-10-09 01:04:32,382] {base_task_runner.py:95} INFO - Subtask: 
[2018-10-09 01:04:32,385] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:32,385] {bash_operator.py:90} INFO - Output:
[2018-10-09 01:04:33,342] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:33,342] {bash_operator.py:94} INFO - /home/ec2-user/sample_labelsaa: No such file or directory
[2018-10-09 01:04:34,209] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:34,208] {bash_operator.py:94} INFO - /home/ec2-user/sample_labelsab: No such file or directory
[2018-10-09 01:04:35,115] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:35,115] {bash_operator.py:94} INFO - /home/ec2-user/sample_labelsac: No such file or directory
[2018-10-09 01:04:35,982] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:35,981] {bash_operator.py:94} INFO - /home/ec2-user/sample_labelsad: No such file or directory
[2018-10-09 01:04:35,984] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:35,983] {bash_operator.py:97} INFO - Command exited with return code 1
[2018-10-09 01:04:35,987] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:35,984] {models.py:1417} ERROR - Bash command failed
[2018-10-09 01:04:35,987] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-10-09 01:04:35,987] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1374, in run
[2018-10-09 01:04:35,987] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-10-09 01:04:35,987] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 100, in execute
[2018-10-09 01:04:35,987] {base_task_runner.py:95} INFO - Subtask:     raise AirflowException("Bash command failed")
[2018-10-09 01:04:35,987] {base_task_runner.py:95} INFO - Subtask: AirflowException: Bash command failed
[2018-10-09 01:04:35,987] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:35,985] {models.py:1441} INFO - Marking task as FAILED.
[2018-10-09 01:04:36,000] {base_task_runner.py:95} INFO - Subtask: [2018-10-09 01:04:36,000] {models.py:1462} ERROR - Bash command failed
[2018-10-09 01:04:36,000] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-10-09 01:04:36,000] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/bin/airflow", line 28, in <module>
[2018-10-09 01:04:36,001] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-10-09 01:04:36,007] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/bin/cli.py", line 422, in run
[2018-10-09 01:04:36,007] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-10-09 01:04:36,007] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-10-09 01:04:36,007] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-10-09 01:04:36,007] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1374, in run
[2018-10-09 01:04:36,007] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-10-09 01:04:36,007] {base_task_runner.py:95} INFO - Subtask:   File "/usr/local/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 100, in execute
[2018-10-09 01:04:36,007] {base_task_runner.py:95} INFO - Subtask:     raise AirflowException("Bash command failed")
[2018-10-09 01:04:36,008] {base_task_runner.py:95} INFO - Subtask: airflow.exceptions.AirflowException: Bash command failed
[2018-10-09 01:04:36,488] {jobs.py:2083} INFO - Task exited with return code 1
